Vagrant.configure("2") do |config|
  config.vm.box = "dfarrell07/opendaylight"

  config.vm.network "forwarded_port", guest: 8181, host: 8181, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.provision "shell", path: "provision.sh"  
end
